# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a5dde8b281df60e66bbe78c696f7372fabdfb4b42bfa6c0cb9395af53ad58af83c6b494e834242d9adabbb10a19784cfd24274a59bc41d09f70eed3e88e9885

test:
  secret_key_base: 603e5f41c454800e5d144a9db3e862192fc256dfa91000872fc7093d9c35ef5549d2097664f9436194b55c629e4565ff1ecab4ff7e9340b7397170ac171915a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  sms_ru_api_id: <%= ENV["SMS_RU_API_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  apn_certificate: "<%= ENV["APN_CERTIFICATE"] %>"
  apn_environment: <%= ENV["APN_ENVIRONMENT"] %>
  gcm_api_key: <%= ENV["GCM_API_KEY"] %>
  alfabank_username: <%= ENV["ALFABANK_USERNAME"] %>
  alfabank_password: <%= ENV["ALFABANK_PASSWORD"] %>
  alfabank_binding_username: <%= ENV["ALFABANK_BINDING_USERNAME"] %>
  alfabank_binding_password: <%= ENV["ALFABANK_BINDING_PASSWORD"] %>
  alfabank_mode: <%= ENV["ALFABANK_MODE"] %>
  alfabank_return_url: "<%= ENV["ALFABANK_RETURN_URL"] %>"
  mailgun_smtp_login: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
  mailgun_smtp_password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
